### PR TITLE
Requests handling cleanup

### LINKED ISSUE #107: Doubtful `RestRequest` need.
I'm not so sure if we need this service since every endpoint now represents single resource. It could be much easier to pass repository service name in generated route option. That's all we need to repeat functionality of this service.

### LINKED ISSUE #109: Other routes does not work when ApiBundle is enabled
Currently exception is thrown when trying to load other than API route. Will be possibly solved together with #108.

### PR DESCRIPTION
**Pull request by murnieza**
Not necessary `RestRequest` object removed. Closes #107
Other routes now works as well. Closes #109

### CODE REVIEW

File: Controller/RestController.php [hunk 1]
```diff
@@ -25,23 +26,32 @@ class RestController extends AbstractRestController implements
...
      * {@inheritdoc}
      */
-    public function getAction(RestRequest $restRequest, $id)
+    public function getAction(Request $request, $id)
     {
+        $repository = $this->getRequestRepository($request);
+
         try {
-            $row = $this->getCrud()->read($restRequest->getRepository(), $id);
+            $row = $this->getCrud()->read($repository, $id);
```
Comment (saimaz) [inline Controller/RestController.php]: `$row` should be called as `$document`

File: Service/RequestSerializer.php [hunk 2]
```diff
@@ -0,0 +1,98 @@
...
+    /**
+     * Returns acceptance type based on given request.
+     *
+     * @return string
+     */
+    public function checkAcceptHeader(Request $request)
+    {
+        $headers = $request->getAcceptableContentTypes();
+
+        if (array_intersect($headers, ['application/xml', 'text/xml'])) {
```
Comment (saimaz) [inline Service/RequestSerializer.php]: Should be switch
