### PR TITLE
Fixed tests, changed controller from string to array in config.

### LINKED ISSUE #36: Change default controller from string to array in config.
Also array keys in controller array should be changed to more intuitive. Instead of
``` yaml
controller:
    controller: AcmeTestBundle:CustomApi
```
could be, for example:
``` yaml
controller:
    name: AcmeTestBundle:CustomApi
```

### PR DESCRIPTION
**Pull request by emaslak**
Closes #36 and #37

### CODE REVIEW

File: DependencyInjection/Configuration.php [hunk 1]
```diff
@@ -66,7 +66,9 @@ public function getConfigTreeBuilder()
                                         ->end()
                                         ->arrayNode('controller')
                                             ->children()
-                                                ->scalarNode('controller')->isRequired()->end()
+                                                ->scalarNode('name')
+                                                    ->isRequired()
```
Comment (GrandLTU) [inline DependencyInjection/Configuration.php]: add `->defaultValue('default')` here and `->addDefaultsIfNotSet()` to array node that way there would be no need to verify it in extension.
